baseURL = 'https://saasblogui.onrender.com/'
languageCode = 'en-us'
title = 'CloudCashflow'
theme = "blogTheme"
summarylength = 20
enableRobotsTXT = true


[permalinks]
blog = "/:year/:title/"

[Params]
    pageSize = 7
    Description = "Want to start a successful SaaS business? Discover innovative SaaS and micro SaaS ideas to launch your next profitable venture."
    Keyword = "saas, saas builder, saas ideas, no-code saas, micro-saas, micro saas, micro-sass ideas, micro saas companies, b2b saas ideas, startup apps ideas"

[markup.goldmark.renderer]
    unsafe = true # Allow HTML in md files

[markup]
    [markup.tableOfContents]
        endLevel = 4
        ordered = false
        startLevel = 1
